### PR TITLE
Add premultiply alpha option (default)

### PR DESCRIPTION
**Pull request by trigger-segfault**
By default, XNB's will now have their alpha premultiplied unless otherwise specified. This fixes issue https://github.com/sullerandras/png_to_xnb/issues/5.

**Argument:** `[-nopre]`
**Details:** Premultiplying alpha is the process of scaling the RGB channels by the alpha (as 0.0-1.0). XNB's created in XNA or other official tools will, *by default*, premultiply the alpha.

**Other Changes:**
* Changed width of `checkBoxCompress` to make room for `checkBoxPremultiply`.
* Simplified `Path.Combine(Path.GetDirectory(), Path.GetFileNameWithoutExtension() + ext)` to `Path.ChangedExtension()`.
* Open File Dialog now properly states *.xnb as *XNB files* and not *PNG files*.
* Added "if" to "even **if** xcompress32.dll is available" in `-u` argument description.

### CODE REVIEW

**Review by sullerandras — APPROVED** [review]
Looking very good, thanks! Any chance you can add the precompiled exe file?

**Comment by trigger-segfault** [comment]
All set!

**Comment by sullerandras** [comment]
@trigger-death Thanks a lot!

**Comment by Rombersoft** [comment]
Hey guys, your fixing has not given result.
I have png with round corners (a=0-255, r=255, g=255, b=255)
and result xnb has black curve lines where pixels have half transparent color

source
index

result
[index.zip](https://github.com/sullerandras/png_to_xnb/files/2361128/index.zip)

result reflection on application
png_to_xnb_result

**Comment by Rombersoft** [comment]
I'm stupid. I've not noticed that you added new option -nopre.

**Comment by Rombersoft** [comment]
So problem was resolved partial.
If I do 
```
SpriteBatch.Begin((SpriteSortMode)0,
                null,
                null,
                null,
                null,
                null,
                Matrix.CreateScale(Common.Instance.ResolutionScale[0], Common.Instance.ResolutionScale[1], 1));
```
That I see corners

But if I do
```
spriteBatch.Begin(SpriteSortMode.Immediate, 
                BlendState.NonPremultiplied, 
                null, 
                null, 
                null,
                null,
                Microsoft.Xna.Framework.Matrix.CreateScale(1, 1, 1));
```
that I see round corner. But I don't need BlendState.NonPremultiplied bacause it distorts half-transpared image with rgb close to black.

Only microsoft company makes it good but I don't have windows servers

**Pull request merged**
